[env:iffmesh]
extends = esp32s3_base
board = iffmesh_reva
board_build.partitions = default_8MB.csv
upload_protocol = esptool

build_flags = 
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/iffmesh
  -D IFFMESH_REVA
lib_deps =
  ${esp32s3_base.lib_deps}
